---


- hosts: compute
  user: root
  connection: local
  tasks:
    - yum:
        name="vim"
        state=installed

- hosts: login
  user: root
  connection: local
  tasks:
    - yum:
        name="mysql"
        state=installed
