---

- hosts: all
  user: root
  connection: local
  tasks:
    - name: general yum packages
      yum: pkg={{ item }} state=installed disable_gpg_check=true
      with_items:
        - vim
        - openldap
        - openldap-clients
        - nss-pam-ldapd
        - pam_ldap
        - nscd
        - authconfig
        - tcl
        - lua
        - lua-posix
        - lua-filesystem
        - ipython

    - name: ldap auth
      command: authconfig --enableldap --enableldapauth --ldapserver=ldap://ldap.localdomain:389/ --ldapbasedn="dc=localdomain" --enablecache --disablefingerprint --kickstart

    - name: mount home
      mount: name=/home src='vault:/home' fstype=nfs state=mounted
    - name: mount opt
      mount: name=/opt src='vault:/opt' fstype=nfs state=mounted


- hosts: compute
  user: root
  connection: local
  tasks:
    - name: compute yum packages disable_gpg_check=true
      yum: pkg={{ item }} state=installed
      with_items:
        - torque


- hosts: login
  user: root
  connection: local
  tasks:
    - name: login yum packages 
      yum: pkg={{ item }} state=installed disable_gpg_check=true
      with_items:
        - mysql
        - mysql-server
        - tmux
        - '@development'
        - tig
        - lua-devel
