---

- hosts: all
  user: root
  connection: local
  tasks:
    - name: general yum packages
      yum: pkg={{ item }} state=installed disable_gpg_check=true
      with_items:
        - vim
        - emacs
        - gnuplot
        - '@development'
        - hwloc
        - tig
        - rdma
        - libibverbs
        - hwloc
        - openldap
        - openldap-clients
        - nss-pam-ldapd
        - pam_ldap
        - nscd
        - authconfig

    - name: ldap auth
      command: authconfig --enableldap --enableldapauth --ldapserver=ldap://ldap.localdomain:389/ --ldapbasedn="dc=localdomain" --enablecache --disablefingerprint --kickstart


- hosts: compute
  user: root
  connection: local
  tasks:
    - name: compute yum packages disable_gpg_check
      yum: pkg={{ item }} state=installed
      with_items:
        - torque


- hosts: login
  user: root
  connection: local
  tasks:
    - name: login yum packages 
      yum: pkg={{ item }} state=installed disable_gpg_check
      with_items:
        - mysql
        - mysql-server
        - tmux
